{
#  公众号配置
#  公众号appId
"app_id": "wxcb1d2eeb4ba5b440",
#  公众号appSecret
"app_secret": "3bd4765ae8b3ccbdc73601f3b26a9acd",
#  模板消息id
"template_id": "G_iq7yamcijsik06rbHCdK_fiDCyOTcUS-HTcp9zdsQ",
#  接收公众号消息的微信号
"user": "opAFR6T1YVH3wP8tXL_Ku6-EigVw",

#  信息配置
#  所在城市
"city": "上海",
}
